Python 3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
search = {'Access':'அணுக்கம்',
          'Accuracy':'துல்லியம்',
          'Action':'செயல்',
          'Activate':'இயக்கு',
          'Active cell':'இயங்கு கலன்',
          'Active file':'நடப்புக் கோப்பு',
          'Activity':'செயல்பாடு',
          'Adapter card':'பொருத்து அட்டை',
          'Adaptor':'பொருத்தி',
          'Address':'முகவரி',
          'Address bus':'முகவரி பாட்டை',
          'Address modification':'முகவரி மாற்றம்',
          'Addressing':'	முகவரியிடல்',
          'Administrator':'நிர்வாகி',
          'Album':'தொகுப்பு',
          'Algorithm language':'நெறிப்பாட்டு மொழி',
          'Algorithm':'நெறிமுறை',
          'Alignment':'இசைவு',
          'Allocation':'ஒதுக்கீடு',
          'Alpha testing':'முதற்கட்ட சோதனை',
          'Alphabet':'அகரவரிசை/நெடுங்கணக்கு',
          'Alphabetical':'அகர வரிசைப்படி',
          'Alphanumeric':'எண்ணெழுத்து',
          'Ambiguation':'கவர்படுநிலை',
          'Amplified':'பெருக்கப்பட்ட',
          'Analog representation':'ஒப்புமை மீள்வடிவாக்கம்',
          'Analog':'ஒப்புமை',
          'Analytical Engine':'பகுப்பாய்வு பொறி',
          'Animation':'அசைவூட்டம்',
          '	Anonymous':'அநாமதேய',
          'Anti-virus':'நச்சுநிரற்கொல்லி',
          'Appearance':'தோற்றம்',
          'Append':'பின்சேர்',
          'Applet':'குறுநிரல்',
          'Application level':'பயன்பாட்டு நிலை',
          'Application programmer':'பயன்பாட்டு நிரலாளர்',
          'Application programming':'பயன்பாட்டு நிரலாக்கம்',
          '	Application programs':'பயன்பாட்டு நிரல்கள்',
          'Application service provider':'பயன்பாட்டுச் சேவை வழங்குனர்',
          '	Application software':'பயன்பாட்டு மென்பொருள்',
          'Application':'செயலி',
          'Architecture	':'கட்டமைப்பு',
          '	Archive file':'	காப்பகக் கோப்பு',
          '	Archive gateway':'	காப்பக நுழைவாயில்',
          '	Archive':'காப்பகம்',
          '	Archiving':'காப்பகப்படுத்தல்',
          'Area search':'பரப்பில் தேடல்',
          '	Arithmetic':'எண் கணிதம்',
          'Array processor':'	அணிச் செயலி',
          '	Array':'அணி',
          '	Arrow key':'திசை விசை',
          'Artificial intelligence':'செயற்கை நுண்ணறிவு',
          'Assembler':'பொறிமொழியாக்கி',
          'Assembly Language':'பொறி மொழி',
          '	Audio blog':'ஒலிதப்பதிவு',
          'Audio':'	ஒலிதம்',
          'Auto block':'தானியங்கித் தடை',
          'Auto restart':'தானியக்க மீள்தொடக்கம்',
          'Automated data processing':'தன்னியக்கத் தரவுச் செயலாக்கம்',
          '	Automatic':'தன்னியக்க',
          '	Auxiliary equipments':'துணைக்கருவிகள்',
          '	Auxiliary function':'துணைச்செயற்கூறு',
          'Auxiliary memory':'துணை நினைவகம்',
          '	Auxiliary operation':'துணை செயல்பாடு',
          '	Auxiliary storage':'துணை தேக்கம்',
          'Availability':'	கிடைத்தல்',
          'Axes':'அச்சுகள்',
          '	Back up':'காப்புநகல்',
          'Background':'பின்னணி',
          'Backspace':'பின்நகர்வு',
          'Bar chart':'பட்டை வரைப்படம்',
          'Bar code':'பட்டைக்குறிமுறை',
          'Bar code scanner':'பட்டைக்குறிமுறை வருடி',
          'Bar printer':'பட்டை அச்சுப்பொறி',
          'Basic':'அடிப்படை',
          'Batch processing':'தொகுதிச்செயலாக்கம்',
          'Beta':'	அறிமுகப் பதிப்பு',
          'Binary Code':'இரும குறிமுறை',
          'Binary device':'இருமக் கருவி',
          'Binary digit':'	இரும இலக்கம்',
          'Binary number':'இரும எண்',
          'Binary operation':'இரும செயற்பாடு',
          'Binary system':'இரும கட்டகம்',
          'Bit map display':'நுண் படக் காட்சி',
          'Bit map scanning':'நுண் பட வருடி',
          'Bit mapped screen':'நுண் பட திரை',
          'Bit values':'நுண்மியின் மதிப்புகள்',
          'Bit':'நுண்மி',
          'Bitmap':'நுண் படம்',
          'Bit-mapped font':'நுண் பட எழுத்துரு',
          'Blank character':'வெற்றுரு',
          'Blank page':'வெற்றுப்பக்கம்',
          'Blanking':'வெறுமைப்படுத்தல்',
          'Block':'தடை',
          'Blog':'வலைப்பதிவு',
          'Blog info':'வலைப்பதிவு தகவல்கள்',
          'Blog tools':'வலைப்பதிவுக் கருவிகள்',
          'Blogger':'வலைப்பதிவர்',
          'Blogger circle':'வலைப்பதிவர் வட்டம்',
          'Blogging':'வலைப்பதிதல்',
          'Bookmark':'புத்தகக் குறி',
          'Boot':'தொடக்கு',
          'Border':'கரைகள்',
          '	Branching':'கிளைப்பிரிதல்',
          'Bridge':'இணைவி',
          'Broadband':'அகலப்பட்டை',
          'Browser':'உலாவி',
          'Browsing':'உலாவுதல்',
          'Buddy':'நண்பர்',
          'Bug':'வழு',
          'Bug report':'வழு அறிக்கை',
          'Bus':'பாட்டை',
          'Cache':'தேக்கம்',
          'Calculating':'கணக்கிடல்',
          'Calculation':'கணக்கீடு',
          'Calculator mode':'கணிப்பான் நிலை', 
          'Calculator':'கணிப்பான்',
          'Cancel':'தவிர்',
          'Capacity':'கொள்திறன்',
          'Carriage return':'ஏந்தி மீளல்',
          'Catalog':'விவரப்பட்டியல்',
          'Category':'பக்கவகை',
          'CD burning':'குறுவட்டு எரித்தல்',
          'CD player':'இறுவட்டு இயக்கி',
          'Center':'மையம்',
          'Central processing unit ':'மையச் செயலகம்',
          'Central processor':'மையச் செயலி',
          'Chain printer':'தொடர்ப்பதிப்பான்',
          'Change':'மாற்றல்',
          'Channel':'	தடம்',
          'Character':'	வரியுரு',
          'Character code':'வரியுருக் குறி',
          'Character map':'	வரியுரு வரைப்படம்',
          'Character recognition':'	வரியுரு அறிதல்',
          'Character set':'வரியுருக்கணம்',
          'Character string':'	வரியுருச்சரம்',
          '	Chart':'வரைப்படம்',
          '	chat':'அரட்டை',
          'Checkbox':'தேர்வுப்பெட்டி',
          'Chips':'	சில்லுகள்',
          'Clear':'துடை',
          'Click':'சொடுக்கு',
          '	Clipboard':'மறைப்பலகை',
          '	Close':'	மூடு',
          'Closed file':'மூடப்பட்ட கோப்பு',
          '	Cloud computing':'முகிலக் கணிப்பு',
          'Collection':'	திரட்டல்',
          'Color coding':'வண்ணக் குறிமுறை',
          'Color graphics':'வண்ன வரைகலை',
          'Color':'வண்ணம்',
          'Column split':'நெடுவரிசைப் பிரிப்பு',
          '	Column':'நெடுவரிசை',
          'Command key':'கட்டளை விசை',
          'Command':'கட்டளை',
          'Comment':'கருத்துரை',
          'Comments moderation':'கருத்துரை மட்டுறுத்தல்',
          'Common storage':'பொதுத்தேக்கம்',
          'Common':'	பொது',
          '	Communication link':'தொடர்பு இணைப்பு',
          'Communication processor':'தொடர்பு செயலகம்',
          'Communication satellite':'தொடர்பு செயற்கைக்கோள்',
          'Communication software':'தொடர்பு மென்பொருள்',
          'Communication protocols':'தொடர்பு நெறிமுறைகள்',
          'Community portal':'சமுதாய வலைவாசல்',
          'Compact disc':'குறுவட்டு',
          'comparative operator':'ஒப்பீட்டு இயக்கி',
          'Compare':'ஒப்பிடு',
          'Comparison':'ஒப்பிடுதல்',
          'Compilation':'தொகுப்பு',
          'Compiler':'தொகுப்பி',
          'Complier language':'தொகுப்பு மொழி',
          'Component':'உறுப்புக்கூறு',
          'Compress':'அழுத்து',
          'Computer engineer':'கணிப் பொறியாளர்',
          'Computer game':'	கணினி விளையாட்டு',
          'Computer graphic':'கணினி வரைகலை',
          'Computer language':'கணினி (நிரல்) மொழி',
          'Computer motherboard':'கணினி தாய்பலகை',
          '	Computer network':'கணினி வலையமைப்பு',
          'Computer operation':'கணினிச் செயல்பாடுகள்',
          'Computer program':'கணனி நிரல்',
          'Computer resources':'கணினி வளங்கள்',
          'Computer user':'கணினி பயனர்',
          'Computer utility':'கணனி பயனமைப்பு',
          'Computer':'	கணினி',
          'Computerization':'கணினிமயமாக்கல்',
          'Computerized data base':'கணினிமய தரவு தளம்',
          'Computerized data processing':'கணினிமய தரவு செயலாக்கம்',
          'Computing':'கணினிப்பணி',
          'Condition':'நிலை',
          'Configuration':'	அமைவடிமம்',
          'Connectors':'	இணைப்பான்கள்',
          'Console':'முனையம்',
          'Constants':'மாறிலிகள்',
          'Content policy':'உள்ளடக்கக் கொள்கை',
          '	Contributions':'பங்களிப்புகள்',
          'Contributor':'பங்களிப்போர்',
          'Control key':'கட்டுப்பாட்டு விசை',
          'Control panel':'கட்டுப்பாட்டகம்',
          'Control program':'கட்டுப்பாட்டு நிரல்',
          'Control statement':'	கட்டுப்பாட்டுக்கூற்று',
          'Control structure':'	கட்டுப்பாட்டு உருவம்',
          'Control system':'கட்டுப்பாட்டு கட்டகம்',
          'Control unit':'கட்டுப்பாட்டு பிரிவு',
          'Conversion':'மாற்றம்',
          'Convert':'	மாற்று',
          '	Cookie':'நினைவி',
          '	Copy protection':'நகல் காப்பு',
          'Copy':'நகல்',
          'Copyright status':'பதிப்புரிமை நிலை',
          'Copyright':'	பதிப்புரிமை',
          'Core storage':'வளையத் தேக்கம்',
          'Cost analysis':'	விலைப் பகுப்பாய்வு',
          '	Cost benefit analysis':'',
          'விலை பயன் பகுப்பாய்வு':'',
          'Cost effectiveness':'	விலை பயன் திறன்',
          'Create':'உருவாக்கு',
          '	Crop':'	செதுக்கு',
          'Current events':'நடப்பு நிகழ்வுகள்',
          'Curve fitting':'	வளைக்கோட்டுப் பொருத்தம்',
          '	Custom software':'தனிப்பயன் மென்பொருள்',
          'Customize':'தனிப்பயனாக்கு',
          '	Cut':'	வெட்டு',
          'Cyber':'மின்வெளி',
          'Dashboard':'	கட்டுப்பாட்டகம்',
          'Data':'	தரவு',
          'Data catalog':'	தரவு விவரப்பட்டியல்',
          'Data flow':'	தரவுப் பொழிவு',
          'Data processing':'	தரவுச் செயலாக்கம்',
          '	Database':'	தரவுத்தளம்',
          '	Decimal digit':'பதின்ம இலக்கம்',
          'Decimal number':'	பதின்ம எண்',
          'Decimal point':'	பதின்ம புள்ளி',
          'Decimal':'	பதின்மம்',
          'Decode':'நீக்கி',
          '	Decompress':'விரிவாக்கு',
          'Default':'இயல்பிருப்பு',
          'Definite':'தெளிவான',
          'Delete':'	அழி',
          'Deletion':'	அழித்தல்',
          'Description':'விளக்கம்',
          'Design':'வடிவமைப்பு',
          'Desktop computer':'	மேசை கணினி',
          'Desktop':'	முகத்திரை',
          'Destination':'	அடையுமிடம்',
          '	Developer':'	மேம்படுத்துனர்',
          'Device':'	கருவி',
          'Diagram':'	விளக்கப்படம்',
          'Digital':'	எண்மின்',
          'Disambiguated':'தெளிவுப்படுத்திய',
          'Disambiguation':'தெளிவாக்கல்',
          'Discovery':'கண்டறிதல்',
          'Discuss':'கலந்தாலோசி',
          'Disk drive':'வட்டு இயக்கி',
          'Display name':'தோற்றப்பெயர்',
          'Distribute':'வினியோகப்படுத்து',
          '	DNS':'	கொப்பெகம்',
          'Document':'ஆவணம்',
          'Documentation':'	ஆவணமாக்கம்',
          'Domain':'ஆள்களமையம்',
          'Domain Name System':'கொற்றப் பெயர்க் கட்டகம்',
          'Double click':'	இரட்டைச் சொடுக்கு',
          'Download':'	பதிவிறக்கம்',
          'Drag':'இழு',
          'Driver':'இயக்கி',
          'Drum plotter':'	உருளை வரைவு',
          'Drum printer':'உருளை அச்சுப்பொறி',
          'Drum scanner':'உருளை வருடி',
          'E-book':'மென்நூல்',
          'Edit':'மாற்று',
          'Edit profile':'சுயவிபரத்தை மாற்று',
          'Editor':'	தொகுப்பாளர்',
          'Educational software':'அறிவியல் மென்பொருள்',
          'Effective':'பயன்விளையத்தக்க',
          'Effects':'	விளைவுகள்',
          'E-governance':'மின்-அரசாண்மை',
          'Electrical signal':'மின் சமிக்ஞை',
          'Electronic':'	மின்னணு',
          'E-mail':'மின்னஞ்சல்',
          'Embedded':'	பொதிந்துள்ள',
          '	Emulation':'போலச்செய்தல்',
          '	Encoding':'குறியாக்கம்',
          'Encyclopedia':'	கலைக்களஞ்சியம்',
          'End':'	முடிவு',
          'Equation':'சமன்பாடு',
          'Erase':'	அழி',
          'Eraser':'அழிப்பான்',
          'Expansion slots':'	விரிவாக்க செருகுவாய்கள்',
          '	Expiry':'காலாவதி',
          'Extended info':'விரிவாக்கப்பட்ட தகவல்',
          'External links':'வெளி இணைப்புகள்',
          'External search engine':'வெளித்தேடுபொறி',
          'FAQ':'	அடிக்கடி கேட்கப்படும் கேள்விகள்',
          'Features':'அம்சங்கள்',
          'Field':'	புலம்',
          'File':'கோப்பு',
          'File management':'கோப்பு மேலாண்மை',
          'File share':'	கோப்பு பகிர்வான்',
          '	File sharing':'கோப்பு பகிர்தல்',
          'Find':'தேடு',
          'Firewall':'தீயரண்',
          'Firmware':'	நிலைப்பொருள்',
          'Flat monitor':'தட்டை திரையகம்',
          '	Floppy drive':'நெகிழ் வட்டு',
          '	Flow chart':'	நெறிமுறை விளக்கப்படம்',
          '	Folder':'கோப்புறை',
          'Font':'	எழுத்துரு',
          'Font and word processor':'	எழுத்துருவும் சொல் செயலாக்கியும்',
          '	Font name':'	எழுத்துரு பெயர்',
          'Footer':'அடிப்பாகம்',
          '	Formal language':'	வடிவ மொழி',
          'Format':'வடிவூட்டம்',
          'Formatting':'வடிவமைத்தல்',
          'Formula':'சூத்திரம்',
          'Free software':'	இலவச மென்பொருள்',
          'Function':'செயற்பாடு',
          'Gallery':'காட்சியகம்',
          'Gateway':'நுழைவாயில்',
          'Global dashboard':'கோளக் கட்டுப்பாட்டகம்',
          '	Global Positioning system':'கோள இருப்பிடக் கட்டகம்',
          'Grammar checker':'இலக்கணத் திருத்தி',
          'Graphic':'வரைகலை',
          '	Group':'குழுமம்',
          'Guest':'விருந்தினர்',
          'Hand held devices':'கையடக்கக் கருவிகள்',
          'Hand held Scanner':'	கையடக்க வருடுபொறி',
          'Handwriting recognition':'கையெழுத்து அறிதல்',
          'Hard disc':'	வன்வட்டு',
          'Hardware':'	வன்பொருள்',
          'Header':'தலைப்பு',
          'Help center':'உதவி மையம்',
          'Help group':'	உதவி குழுமம்',
          'High speed computer':'அதிவேகக் கணினி',
          'Higher level language':'	உயர்நிலை மொழி',
          '	Home':'	முகப்பு',
          '	Homepage':'முகப்புப்பக்கம்',
          'Horizontal line':'	கிடைக்கோடு',
          'Host computer	':'புரவலர் கணினி',
          '	Hyphenation':'	சொல் பிரித்தல்',
          'Icon':'படவுரு',
          '	Identity':'அடையாளம்',
          'iDNS':'வலைக்கொற்றப் பெயர்க் கட்டகம்',
          'iDomain':'வலைக்கொற்றம்',
          '	Ignore':'	புறக்கணி',
          '	Image':'	படிமம்',
          'Import':'இறக்கம்',
          'Incompatible':'முரண்பாடு',
          'Indefinite':'	திட்டமிடாத',
          'Index':'	சுட்டெண்',
          '	Index variable':'சுட்டுமாறி',
          '	Information':'	தகவல்',
          'Information data':'தகவல் தரவு',
          'Information super highways':'	தகவல் மீப் பெருவழிகள்',
          '	Information technology':'தகவல் தொழில்நுட்பம்',
          '	Input unit':'	உள்ளீட்டுப் பகுதி',
          'Insert':'செருகு',
          'Install':'	நிறுவு',
          'Installation':'	நிறுவுதல்',
          '	Integrated chips':'சுற்றமைப்புச் சில்லுகள்',
          'Integrated circuit chips':'ஒருங்கிணைப்பு சுற்றமைப்புச் சில்லுகள்',
          '	Inter language':'	மொழியிடை',
          'Interactive sites':'ஊடாட்ட தளங்கள்',
          'Interests':'ஆர்வங்கள்',
          'Interface':'இடைமுகப்பு',
          'Internal':'உள்ளக',
          'Internal error':'உள்ளகத் தவறு',
          'International':'	பன்னாட்டு',
          'International (DNS)':'	பன்னாட்டுக் (கொப்பெகம்)',
          '	Internet':'இணையம்',
          'Internet protocol address':'இணைய நெறிமுறை முகவரி',
          'Internet protocol (IP)':'	இணைய நெறிமுறை',
          'Internet service provider (ISP)':'இணையச் சேவை வழங்குனர்',
          'Interpreter':'இடைமாற்று',
          'Invalid':'செல்லுபடியாகாத',
          'Invention':'கண்டுப்பிடிப்பு',
          '	Italic text':'	சாய்வெழுத்து',
          'Iteration':'பன்முறைச் செய்தல்',
          'Java script':'	ஜாவா ஆணைத்தொகுதி',
          'Key':'	விசை',
          'Keyboard':'தட்டச்சுப்பலகை',
          'Keypad':'விசைத்தளம்',
          'Keyword':'	குறிப்புச்சொல்',
          'Landscape':'	அகலவாக்கி',
          '	Laptop computer':'	மடிக்கணினி',
          'Layout':'	தளவமைப்பு',
          'LCD Monitor':'திரவ பளிங்குத் திரையகம்',
          'Left click':'	இடதுச் சொடுக்கு',
          'Lexing error':'தொகுத்தல் தவறு',
          'License':'	உரிமம்',
          'Light pen':'எழுதுகோல்',
          'Line':'வரி',
          '	Link':'தொடுப்பு',
          'List':'பட்டியல்',
          'Live':'நேரடி',
          'Log in':'உற்புகு',
          'Log out':'வெளியேறு',
          'Machine language':'	பொறிமொழி',
          'Machine translation':'எந்திர மொழிபெயர்ப்பு',
          'Magnetic disk':'காந்த வட்டு',
          'Magnetic tape':'	காந்தா நாடா',
          'Main Page':'முகப்புப்பக்கம்',
          'Maintenance page':'மேலாண்மைப் பக்கம்',
          '	Management':'முகாமைத்துவம்',
          'Mechanical calculator':'எந்திர கணிப்பான்',
          'Media':'	ஊடகம்',
          'Media player':'	ஊடக இயக்கி',
          'Memory unit':'	நினைவகப் பகுதி',
          'Memory':'நினைவகம்',
          'Menu':'	பட்டியல்',
          'Metadata':'தரவு விவரம்',
          'Micro processor':'	நுண் செயலி',
          'Microphone':'	ஒலிவாங்கி',
          'Modem':'	இணக்கி',
          'Moderation':'மட்டுறுத்தல்',
          'Moderator':'மட்டுறுத்துனர்',
          'Monetize':'மதிப்புடைச்செய்',
          'Monitor':'திரையகம்',
          'More features':'	கூடுதல் அம்சங்கள்',
          'Motherboard':'	தாய்ப்பலகை',
          'Mouse':'	சொடுக்கி',
          '	Multimedia':'பல்லூடகம்',
          'Multitasking':'பல்பணியாக்கம்',
          'My account':'எனது கணக்கு',
          'Natural language':'இயற்கை மொழி',
          'Navigation':'வழிசெலுத்தல்',
          'Negative':'எதிர்வு',
          '	Network':'வலையமைப்பு',
          'Networking':'வலைப்பின்னல்',
          'Neutral point of view':'	நடுநிலைநோக்கு',
          'New post':'	புதிய இடுகை',
          'Non-terminals':'	முடியா முனையங்கள்',
          'Notation':'குறிமானம்',
          'Note':'	குறிப்பு',
          'Number':'எண்',
          'Numeral':'	எண் முறை',
          '	Object':'	பொருள்',
          'Offline':'இணைப்பின் வெளியே',
          'Online':'இணைப்பில்',
          'Operating system':'இயங்குக் கட்டகம்',
          'Option':'	தேர்வு',
          'Orphaned pages':'	உறவிலிப் பக்கங்கள்',
          'Other languages	':'ஏனைய மொழிகள்',
          '	Outsourcing':'	அயலாக்கம்',
          'Package':'	பொதி',
          'Packets':'பொதிகள்',
          'Page layout':'	பக்க வடிவமைப்பு',
          '	Page views':'	பக்கப் பார்வைகள்',
          'Page':'பக்கம்',
          '	Panel':'	பலகை',
          'Paperless office':'தாளில்லா அலுவலகம்',
          '	Paragraph':'	பந்தி',
          'Parallel processing computers':'இணைச் செயலாக்க கணினிகள்',
          'Parent category':'	முதன்மை பக்கவகை',
          'Password':'	கடவுச்சொல்',
          'Paste':'	ஒட்டு',
          '	Patch':'	பொருத்து',
          'Peripherals':'	உபகரணங்கள்',
          'Permission':'	அனுமதி',
          'Personal Computer':'	தனி கணினி',
          'Photograph':'	புகைப்படம்',
          'Picture':'	படம்',
          '	Piracy':'களவுநகலாக்கம்',
          'Plug in':'சொருகி',
          'Pointer':'சுட்டு',
          'Portable Printer':'கையடக்க அச்சுப்பொறி',
          'Portal':'வலைவாசல்',
          'Post':'	இடுகை',
          'Posting':'இடுகையிடல்',
          '	Posts':'இடுகைகள்',
          'Preferences':'விருப்புத்தேர்வுகள்',
          'Presentation':'அளிக்கை',
          'Press':'	அமுக்கு',
          'Preview':'முன்தோற்றம்',
          'Principals':'	கோட்பாடு',
          '	Print':'	அச்சிடு',
          'Printer':'அச்சுப்பொறி',
          '	Privacy':'தனிமறைவு',
          'Problem':'பிரச்சினை',
          '	Processor':'	செயலி',
          '	Program':'	நிரல்',
          'Programmers':'நிரலர்கள்',
          'Programming language':'நிரலாக்க மொழி',
          'Prompt':'	தூண்டி',
          'Protect':'காப்புச்செய்',
          'Protection log':'தடைப்பதிகை',
          'Protocols':'	நெறிமுறைகள்',
          'Proxy Server':'பதில் சேவையகம்',
          'Public domain':'பொதுக்களம்',
          'Publications':'	வெளியீடுகள்',
          '	Publish':'வெளியிடு',
          'Publisher':'பதிப்பாளர்',
          '	Publishing':'	பதிப்பிடல்',
          'Query':'வினவல்',
          '	RAM':'	நினைவகம்',
          'Random Page':'ஒழுங்கிலாப் பக்கம்',
          'Recent changes':'அண்மைய மாற்றங்கள்',
          'Recovery tool':'	மீட்சி கருவி',
          'Redirects':'	வழிமாற்றிகள்',
          'Redo':'திரும்பச்செய்',
          'Reference desk':'எடுகோள் மேடை',
          }
type(search)
<class 'dict'>

d_key=[]
for i in search.keys():
    d_key.append(i.strip())

    
d_key
['Access', 'Accuracy', 'Action', 'Activate', 'Active cell', 'Active file', 'Activity', 'Adapter card', 'Adaptor', 'Address', 'Address bus', 'Address modification', 'Addressing', 'Administrator', 'Album', 'Algorithm language', 'Algorithm', 'Alignment', 'Allocation', 'Alpha testing', 'Alphabet', 'Alphabetical', 'Alphanumeric', 'Ambiguation', 'Amplified', 'Analog representation', 'Analog', 'Analytical Engine', 'Animation', 'Anonymous', 'Anti-virus', 'Appearance', 'Append', 'Applet', 'Application level', 'Application programmer', 'Application programming', 'Application programs', 'Application service provider', 'Application software', 'Application', 'Architecture', 'Archive file', 'Archive gateway', 'Archive', 'Archiving', 'Area search', 'Arithmetic', 'Array processor', 'Array', 'Arrow key', 'Artificial intelligence', 'Assembler', 'Assembly Language', 'Audio blog', 'Audio', 'Auto block', 'Auto restart', 'Automated data processing', 'Automatic', 'Auxiliary equipments', 'Auxiliary function', 'Auxiliary memory', 'Auxiliary operation', 'Auxiliary storage', 'Availability', 'Axes', 'Back up', 'Background', 'Backspace', 'Bar chart', 'Bar code', 'Bar code scanner', 'Bar printer', 'Basic', 'Batch processing', 'Beta', 'Binary Code', 'Binary device', 'Binary digit', 'Binary number', 'Binary operation', 'Binary system', 'Bit map display', 'Bit map scanning', 'Bit mapped screen', 'Bit values', 'Bit', 'Bitmap', 'Bit-mapped font', 'Blank character', 'Blank page', 'Blanking', 'Block', 'Blog', 'Blog info', 'Blog tools', 'Blogger', 'Blogger circle', 'Blogging', 'Bookmark', 'Boot', 'Border', 'Branching', 'Bridge', 'Broadband', 'Browser', 'Browsing', 'Buddy', 'Bug', 'Bug report', 'Bus', 'Cache', 'Calculating', 'Calculation', 'Calculator mode', 'Calculator', 'Cancel', 'Capacity', 'Carriage return', 'Catalog', 'Category', 'CD burning', 'CD player', 'Center', 'Central processing unit', 'Central processor', 'Chain printer', 'Change', 'Channel', 'Character', 'Character code', 'Character map', 'Character recognition', 'Character set', 'Character string', 'Chart', 'chat', 'Checkbox', 'Chips', 'Clear', 'Click', 'Clipboard', 'Close', 'Closed file', 'Cloud computing', 'Collection', 'Color coding', 'Color graphics', 'Color', 'Column split', 'Column', 'Command key', 'Command', 'Comment', 'Comments moderation', 'Common storage', 'Common', 'Communication link', 'Communication processor', 'Communication satellite', 'Communication software', 'Communication protocols', 'Community portal', 'Compact disc', 'comparative operator', 'Compare', 'Comparison', 'Compilation', 'Compiler', 'Complier language', 'Component', 'Compress', 'Computer engineer', 'Computer game', 'Computer graphic', 'Computer language', 'Computer motherboard', 'Computer network', 'Computer operation', 'Computer program', 'Computer resources', 'Computer user', 'Computer utility', 'Computer', 'Computerization', 'Computerized data base', 'Computerized data processing', 'Computing', 'Condition', 'Configuration', 'Connectors', 'Console', 'Constants', 'Content policy', 'Contributions', 'Contributor', 'Control key', 'Control panel', 'Control program', 'Control statement', 'Control structure', 'Control system', 'Control unit', 'Conversion', 'Convert', 'Cookie', 'Copy protection', 'Copy', 'Copyright status', 'Copyright', 'Core storage', 'Cost analysis', 'Cost benefit analysis', 'விலை பயன் பகுப்பாய்வு', 'Cost effectiveness', 'Create', 'Crop', 'Current events', 'Curve fitting', 'Custom software', 'Customize', 'Cut', 'Cyber', 'Dashboard', 'Data', 'Data catalog', 'Data flow', 'Data processing', 'Database', 'Decimal digit', 'Decimal number', 'Decimal point', 'Decimal', 'Decode', 'Decompress', 'Default', 'Definite', 'Delete', 'Deletion', 'Description', 'Design', 'Desktop computer', 'Desktop', 'Destination', 'Developer', 'Device', 'Diagram', 'Digital', 'Disambiguated', 'Disambiguation', 'Discovery', 'Discuss', 'Disk drive', 'Display name', 'Distribute', 'DNS', 'Document', 'Documentation', 'Domain', 'Domain Name System', 'Double click', 'Download', 'Drag', 'Driver', 'Drum plotter', 'Drum printer', 'Drum scanner', 'E-book', 'Edit', 'Edit profile', 'Editor', 'Educational software', 'Effective', 'Effects', 'E-governance', 'Electrical signal', 'Electronic', 'E-mail', 'Embedded', 'Emulation', 'Encoding', 'Encyclopedia', 'End', 'Equation', 'Erase', 'Eraser', 'Expansion slots', 'Expiry', 'Extended info', 'External links', 'External search engine', 'FAQ', 'Features', 'Field', 'File', 'File management', 'File share', 'File sharing', 'Find', 'Firewall', 'Firmware', 'Flat monitor', 'Floppy drive', 'Flow chart', 'Folder', 'Font', 'Font and word processor', 'Font name', 'Footer', 'Formal language', 'Format', 'Formatting', 'Formula', 'Free software', 'Function', 'Gallery', 'Gateway', 'Global dashboard', 'Global Positioning system', 'Grammar checker', 'Graphic', 'Group', 'Guest', 'Hand held devices', 'Hand held Scanner', 'Handwriting recognition', 'Hard disc', 'Hardware', 'Header', 'Help center', 'Help group', 'High speed computer', 'Higher level language', 'Home', 'Homepage', 'Horizontal line', 'Host computer', 'Hyphenation', 'Icon', 'Identity', 'iDNS', 'iDomain', 'Ignore', 'Image', 'Import', 'Incompatible', 'Indefinite', 'Index', 'Index variable', 'Information', 'Information data', 'Information super highways', 'Information technology', 'Input unit', 'Insert', 'Install', 'Installation', 'Integrated chips', 'Integrated circuit chips', 'Inter language', 'Interactive sites', 'Interests', 'Interface', 'Internal', 'Internal error', 'International', 'International (DNS)', 'Internet', 'Internet protocol address', 'Internet protocol (IP)', 'Internet service provider (ISP)', 'Interpreter', 'Invalid', 'Invention', 'Italic text', 'Iteration', 'Java script', 'Key', 'Keyboard', 'Keypad', 'Keyword', 'Landscape', 'Laptop computer', 'Layout', 'LCD Monitor', 'Left click', 'Lexing error', 'License', 'Light pen', 'Line', 'Link', 'List', 'Live', 'Log in', 'Log out', 'Machine language', 'Machine translation', 'Magnetic disk', 'Magnetic tape', 'Main Page', 'Maintenance page', 'Management', 'Mechanical calculator', 'Media', 'Media player', 'Memory unit', 'Memory', 'Menu', 'Metadata', 'Micro processor', 'Microphone', 'Modem', 'Moderation', 'Moderator', 'Monetize', 'Monitor', 'More features', 'Motherboard', 'Mouse', 'Multimedia', 'Multitasking', 'My account', 'Natural language', 'Navigation', 'Negative', 'Network', 'Networking', 'Neutral point of view', 'New post', 'Non-terminals', 'Notation', 'Note', 'Number', 'Numeral', 'Object', 'Offline', 'Online', 'Operating system', 'Option', 'Orphaned pages', 'Other languages', 'Outsourcing', 'Package', 'Packets', 'Page layout', 'Page views', 'Page', 'Panel', 'Paperless office', 'Paragraph', 'Parallel processing computers', 'Parent category', 'Password', 'Paste', 'Patch', 'Peripherals', 'Permission', 'Personal Computer', 'Photograph', 'Picture', 'Piracy', 'Plug in', 'Pointer', 'Portable Printer', 'Portal', 'Post', 'Posting', 'Posts', 'Preferences', 'Presentation', 'Press', 'Preview', 'Principals', 'Print', 'Printer', 'Privacy', 'Problem', 'Processor', 'Program', 'Programmers', 'Programming language', 'Prompt', 'Protect', 'Protection log', 'Protocols', 'Proxy Server', 'Public domain', 'Publications', 'Publish', 'Publisher', 'Publishing', 'Query', 'RAM', 'Random Page', 'Recent changes', 'Recovery tool', 'Redirects', 'Redo', 'Reference desk']

d_value=[]
for i in search.values():
    d_value.append(i.strip())

    
d_word={d_key[i]:d_value[i] for i in range(len(d_key)}
        
SyntaxError: closing parenthesis '}' does not match opening parenthesis '('
d_word={d_key[i]:d_value[i] for i in range(len(d_key))}
        
d_word
        
{'Access': 'அணுக்கம்', 'Accuracy': 'துல்லியம்', 'Action': 'செயல்', 'Activate': 'இயக்கு', 'Active cell': 'இயங்கு கலன்', 'Active file': 'நடப்புக் கோப்பு', 'Activity': 'செயல்பாடு', 'Adapter card': 'பொருத்து அட்டை', 'Adaptor': 'பொருத்தி', 'Address': 'முகவரி', 'Address bus': 'முகவரி பாட்டை', 'Address modification': 'முகவரி மாற்றம்', 'Addressing': 'முகவரியிடல்', 'Administrator': 'நிர்வாகி', 'Album': 'தொகுப்பு', 'Algorithm language': 'நெறிப்பாட்டு மொழி', 'Algorithm': 'நெறிமுறை', 'Alignment': 'இசைவு', 'Allocation': 'ஒதுக்கீடு', 'Alpha testing': 'முதற்கட்ட சோதனை', 'Alphabet': 'அகரவரிசை/நெடுங்கணக்கு', 'Alphabetical': 'அகர வரிசைப்படி', 'Alphanumeric': 'எண்ணெழுத்து', 'Ambiguation': 'கவர்படுநிலை', 'Amplified': 'பெருக்கப்பட்ட', 'Analog representation': 'ஒப்புமை மீள்வடிவாக்கம்', 'Analog': 'ஒப்புமை', 'Analytical Engine': 'பகுப்பாய்வு பொறி', 'Animation': 'அசைவூட்டம்', 'Anonymous': 'அநாமதேய', 'Anti-virus': 'நச்சுநிரற்கொல்லி', 'Appearance': 'தோற்றம்', 'Append': 'பின்சேர்', 'Applet': 'குறுநிரல்', 'Application level': 'பயன்பாட்டு நிலை', 'Application programmer': 'பயன்பாட்டு நிரலாளர்', 'Application programming': 'பயன்பாட்டு நிரலாக்கம்', 'Application programs': 'பயன்பாட்டு நிரல்கள்', 'Application service provider': 'பயன்பாட்டுச் சேவை வழங்குனர்', 'Application software': 'பயன்பாட்டு மென்பொருள்', 'Application': 'செயலி', 'Architecture': 'கட்டமைப்பு', 'Archive file': 'காப்பகக் கோப்பு', 'Archive gateway': 'காப்பக நுழைவாயில்', 'Archive': 'காப்பகம்', 'Archiving': 'காப்பகப்படுத்தல்', 'Area search': 'பரப்பில் தேடல்', 'Arithmetic': 'எண் கணிதம்', 'Array processor': 'அணிச் செயலி', 'Array': 'அணி', 'Arrow key': 'திசை விசை', 'Artificial intelligence': 'செயற்கை நுண்ணறிவு', 'Assembler': 'பொறிமொழியாக்கி', 'Assembly Language': 'பொறி மொழி', 'Audio blog': 'ஒலிதப்பதிவு', 'Audio': 'ஒலிதம்', 'Auto block': 'தானியங்கித் தடை', 'Auto restart': 'தானியக்க மீள்தொடக்கம்', 'Automated data processing': 'தன்னியக்கத் தரவுச் செயலாக்கம்', 'Automatic': 'தன்னியக்க', 'Auxiliary equipments': 'துணைக்கருவிகள்', 'Auxiliary function': 'துணைச்செயற்கூறு', 'Auxiliary memory': 'துணை நினைவகம்', 'Auxiliary operation': 'துணை செயல்பாடு', 'Auxiliary storage': 'துணை தேக்கம்', 'Availability': 'கிடைத்தல்', 'Axes': 'அச்சுகள்', 'Back up': 'காப்புநகல்', 'Background': 'பின்னணி', 'Backspace': 'பின்நகர்வு', 'Bar chart': 'பட்டை வரைப்படம்', 'Bar code': 'பட்டைக்குறிமுறை', 'Bar code scanner': 'பட்டைக்குறிமுறை வருடி', 'Bar printer': 'பட்டை அச்சுப்பொறி', 'Basic': 'அடிப்படை', 'Batch processing': 'தொகுதிச்செயலாக்கம்', 'Beta': 'அறிமுகப் பதிப்பு', 'Binary Code': 'இரும குறிமுறை', 'Binary device': 'இருமக் கருவி', 'Binary digit': 'இரும இலக்கம்', 'Binary number': 'இரும எண்', 'Binary operation': 'இரும செயற்பாடு', 'Binary system': 'இரும கட்டகம்', 'Bit map display': 'நுண் படக் காட்சி', 'Bit map scanning': 'நுண் பட வருடி', 'Bit mapped screen': 'நுண் பட திரை', 'Bit values': 'நுண்மியின் மதிப்புகள்', 'Bit': 'நுண்மி', 'Bitmap': 'நுண் படம்', 'Bit-mapped font': 'நுண் பட எழுத்துரு', 'Blank character': 'வெற்றுரு', 'Blank page': 'வெற்றுப்பக்கம்', 'Blanking': 'வெறுமைப்படுத்தல்', 'Block': 'தடை', 'Blog': 'வலைப்பதிவு', 'Blog info': 'வலைப்பதிவு தகவல்கள்', 'Blog tools': 'வலைப்பதிவுக் கருவிகள்', 'Blogger': 'வலைப்பதிவர்', 'Blogger circle': 'வலைப்பதிவர் வட்டம்', 'Blogging': 'வலைப்பதிதல்', 'Bookmark': 'புத்தகக் குறி', 'Boot': 'தொடக்கு', 'Border': 'கரைகள்', 'Branching': 'கிளைப்பிரிதல்', 'Bridge': 'இணைவி', 'Broadband': 'அகலப்பட்டை', 'Browser': 'உலாவி', 'Browsing': 'உலாவுதல்', 'Buddy': 'நண்பர்', 'Bug': 'வழு', 'Bug report': 'வழு அறிக்கை', 'Bus': 'பாட்டை', 'Cache': 'தேக்கம்', 'Calculating': 'கணக்கிடல்', 'Calculation': 'கணக்கீடு', 'Calculator mode': 'கணிப்பான் நிலை', 'Calculator': 'கணிப்பான்', 'Cancel': 'தவிர்', 'Capacity': 'கொள்திறன்', 'Carriage return': 'ஏந்தி மீளல்', 'Catalog': 'விவரப்பட்டியல்', 'Category': 'பக்கவகை', 'CD burning': 'குறுவட்டு எரித்தல்', 'CD player': 'இறுவட்டு இயக்கி', 'Center': 'மையம்', 'Central processing unit': 'மையச் செயலகம்', 'Central processor': 'மையச் செயலி', 'Chain printer': 'தொடர்ப்பதிப்பான்', 'Change': 'மாற்றல்', 'Channel': 'தடம்', 'Character': 'வரியுரு', 'Character code': 'வரியுருக் குறி', 'Character map': 'வரியுரு வரைப்படம்', 'Character recognition': 'வரியுரு அறிதல்', 'Character set': 'வரியுருக்கணம்', 'Character string': 'வரியுருச்சரம்', 'Chart': 'வரைப்படம்', 'chat': 'அரட்டை', 'Checkbox': 'தேர்வுப்பெட்டி', 'Chips': 'சில்லுகள்', 'Clear': 'துடை', 'Click': 'சொடுக்கு', 'Clipboard': 'மறைப்பலகை', 'Close': 'மூடு', 'Closed file': 'மூடப்பட்ட கோப்பு', 'Cloud computing': 'முகிலக் கணிப்பு', 'Collection': 'திரட்டல்', 'Color coding': 'வண்ணக் குறிமுறை', 'Color graphics': 'வண்ன வரைகலை', 'Color': 'வண்ணம்', 'Column split': 'நெடுவரிசைப் பிரிப்பு', 'Column': 'நெடுவரிசை', 'Command key': 'கட்டளை விசை', 'Command': 'கட்டளை', 'Comment': 'கருத்துரை', 'Comments moderation': 'கருத்துரை மட்டுறுத்தல்', 'Common storage': 'பொதுத்தேக்கம்', 'Common': 'பொது', 'Communication link': 'தொடர்பு இணைப்பு', 'Communication processor': 'தொடர்பு செயலகம்', 'Communication satellite': 'தொடர்பு செயற்கைக்கோள்', 'Communication software': 'தொடர்பு மென்பொருள்', 'Communication protocols': 'தொடர்பு நெறிமுறைகள்', 'Community portal': 'சமுதாய வலைவாசல்', 'Compact disc': 'குறுவட்டு', 'comparative operator': 'ஒப்பீட்டு இயக்கி', 'Compare': 'ஒப்பிடு', 'Comparison': 'ஒப்பிடுதல்', 'Compilation': 'தொகுப்பு', 'Compiler': 'தொகுப்பி', 'Complier language': 'தொகுப்பு மொழி', 'Component': 'உறுப்புக்கூறு', 'Compress': 'அழுத்து', 'Computer engineer': 'கணிப் பொறியாளர்', 'Computer game': 'கணினி விளையாட்டு', 'Computer graphic': 'கணினி வரைகலை', 'Computer language': 'கணினி (நிரல்) மொழி', 'Computer motherboard': 'கணினி தாய்பலகை', 'Computer network': 'கணினி வலையமைப்பு', 'Computer operation': 'கணினிச் செயல்பாடுகள்', 'Computer program': 'கணனி நிரல்', 'Computer resources': 'கணினி வளங்கள்', 'Computer user': 'கணினி பயனர்', 'Computer utility': 'கணனி பயனமைப்பு', 'Computer': 'கணினி', 'Computerization': 'கணினிமயமாக்கல்', 'Computerized data base': 'கணினிமய தரவு தளம்', 'Computerized data processing': 'கணினிமய தரவு செயலாக்கம்', 'Computing': 'கணினிப்பணி', 'Condition': 'நிலை', 'Configuration': 'அமைவடிமம்', 'Connectors': 'இணைப்பான்கள்', 'Console': 'முனையம்', 'Constants': 'மாறிலிகள்', 'Content policy': 'உள்ளடக்கக் கொள்கை', 'Contributions': 'பங்களிப்புகள்', 'Contributor': 'பங்களிப்போர்', 'Control key': 'கட்டுப்பாட்டு விசை', 'Control panel': 'கட்டுப்பாட்டகம்', 'Control program': 'கட்டுப்பாட்டு நிரல்', 'Control statement': 'கட்டுப்பாட்டுக்கூற்று', 'Control structure': 'கட்டுப்பாட்டு உருவம்', 'Control system': 'கட்டுப்பாட்டு கட்டகம்', 'Control unit': 'கட்டுப்பாட்டு பிரிவு', 'Conversion': 'மாற்றம்', 'Convert': 'மாற்று', 'Cookie': 'நினைவி', 'Copy protection': 'நகல் காப்பு', 'Copy': 'நகல்', 'Copyright status': 'பதிப்புரிமை நிலை', 'Copyright': 'பதிப்புரிமை', 'Core storage': 'வளையத் தேக்கம்', 'Cost analysis': 'விலைப் பகுப்பாய்வு', 'Cost benefit analysis': '', 'விலை பயன் பகுப்பாய்வு': '', 'Cost effectiveness': 'விலை பயன் திறன்', 'Create': 'உருவாக்கு', 'Crop': 'செதுக்கு', 'Current events': 'நடப்பு நிகழ்வுகள்', 'Curve fitting': 'வளைக்கோட்டுப் பொருத்தம்', 'Custom software': 'தனிப்பயன் மென்பொருள்', 'Customize': 'தனிப்பயனாக்கு', 'Cut': 'வெட்டு', 'Cyber': 'மின்வெளி', 'Dashboard': 'கட்டுப்பாட்டகம்', 'Data': 'தரவு', 'Data catalog': 'தரவு விவரப்பட்டியல்', 'Data flow': 'தரவுப் பொழிவு', 'Data processing': 'தரவுச் செயலாக்கம்', 'Database': 'தரவுத்தளம்', 'Decimal digit': 'பதின்ம இலக்கம்', 'Decimal number': 'பதின்ம எண்', 'Decimal point': 'பதின்ம புள்ளி', 'Decimal': 'பதின்மம்', 'Decode': 'நீக்கி', 'Decompress': 'விரிவாக்கு', 'Default': 'இயல்பிருப்பு', 'Definite': 'தெளிவான', 'Delete': 'அழி', 'Deletion': 'அழித்தல்', 'Description': 'விளக்கம்', 'Design': 'வடிவமைப்பு', 'Desktop computer': 'மேசை கணினி', 'Desktop': 'முகத்திரை', 'Destination': 'அடையுமிடம்', 'Developer': 'மேம்படுத்துனர்', 'Device': 'கருவி', 'Diagram': 'விளக்கப்படம்', 'Digital': 'எண்மின்', 'Disambiguated': 'தெளிவுப்படுத்திய', 'Disambiguation': 'தெளிவாக்கல்', 'Discovery': 'கண்டறிதல்', 'Discuss': 'கலந்தாலோசி', 'Disk drive': 'வட்டு இயக்கி', 'Display name': 'தோற்றப்பெயர்', 'Distribute': 'வினியோகப்படுத்து', 'DNS': 'கொப்பெகம்', 'Document': 'ஆவணம்', 'Documentation': 'ஆவணமாக்கம்', 'Domain': 'ஆள்களமையம்', 'Domain Name System': 'கொற்றப் பெயர்க் கட்டகம்', 'Double click': 'இரட்டைச் சொடுக்கு', 'Download': 'பதிவிறக்கம்', 'Drag': 'இழு', 'Driver': 'இயக்கி', 'Drum plotter': 'உருளை வரைவு', 'Drum printer': 'உருளை அச்சுப்பொறி', 'Drum scanner': 'உருளை வருடி', 'E-book': 'மென்நூல்', 'Edit': 'மாற்று', 'Edit profile': 'சுயவிபரத்தை மாற்று', 'Editor': 'தொகுப்பாளர்', 'Educational software': 'அறிவியல் மென்பொருள்', 'Effective': 'பயன்விளையத்தக்க', 'Effects': 'விளைவுகள்', 'E-governance': 'மின்-அரசாண்மை', 'Electrical signal': 'மின் சமிக்ஞை', 'Electronic': 'மின்னணு', 'E-mail': 'மின்னஞ்சல்', 'Embedded': 'பொதிந்துள்ள', 'Emulation': 'போலச்செய்தல்', 'Encoding': 'குறியாக்கம்', 'Encyclopedia': 'கலைக்களஞ்சியம்', 'End': 'முடிவு', 'Equation': 'சமன்பாடு', 'Erase': 'அழி', 'Eraser': 'அழிப்பான்', 'Expansion slots': 'விரிவாக்க செருகுவாய்கள்', 'Expiry': 'காலாவதி', 'Extended info': 'விரிவாக்கப்பட்ட தகவல்', 'External links': 'வெளி இணைப்புகள்', 'External search engine': 'வெளித்தேடுபொறி', 'FAQ': 'அடிக்கடி கேட்கப்படும் கேள்விகள்', 'Features': 'அம்சங்கள்', 'Field': 'புலம்', 'File': 'கோப்பு', 'File management': 'கோப்பு மேலாண்மை', 'File share': 'கோப்பு பகிர்வான்', 'File sharing': 'கோப்பு பகிர்தல்', 'Find': 'தேடு', 'Firewall': 'தீயரண்', 'Firmware': 'நிலைப்பொருள்', 'Flat monitor': 'தட்டை திரையகம்', 'Floppy drive': 'நெகிழ் வட்டு', 'Flow chart': 'நெறிமுறை விளக்கப்படம்', 'Folder': 'கோப்புறை', 'Font': 'எழுத்துரு', 'Font and word processor': 'எழுத்துருவும் சொல் செயலாக்கியும்', 'Font name': 'எழுத்துரு பெயர்', 'Footer': 'அடிப்பாகம்', 'Formal language': 'வடிவ மொழி', 'Format': 'வடிவூட்டம்', 'Formatting': 'வடிவமைத்தல்', 'Formula': 'சூத்திரம்', 'Free software': 'இலவச மென்பொருள்', 'Function': 'செயற்பாடு', 'Gallery': 'காட்சியகம்', 'Gateway': 'நுழைவாயில்', 'Global dashboard': 'கோளக் கட்டுப்பாட்டகம்', 'Global Positioning system': 'கோள இருப்பிடக் கட்டகம்', 'Grammar checker': 'இலக்கணத் திருத்தி', 'Graphic': 'வரைகலை', 'Group': 'குழுமம்', 'Guest': 'விருந்தினர்', 'Hand held devices': 'கையடக்கக் கருவிகள்', 'Hand held Scanner': 'கையடக்க வருடுபொறி', 'Handwriting recognition': 'கையெழுத்து அறிதல்', 'Hard disc': 'வன்வட்டு', 'Hardware': 'வன்பொருள்', 'Header': 'தலைப்பு', 'Help center': 'உதவி மையம்', 'Help group': 'உதவி குழுமம்', 'High speed computer': 'அதிவேகக் கணினி', 'Higher level language': 'உயர்நிலை மொழி', 'Home': 'முகப்பு', 'Homepage': 'முகப்புப்பக்கம்', 'Horizontal line': 'கிடைக்கோடு', 'Host computer': 'புரவலர் கணினி', 'Hyphenation': 'சொல் பிரித்தல்', 'Icon': 'படவுரு', 'Identity': 'அடையாளம்', 'iDNS': 'வலைக்கொற்றப் பெயர்க் கட்டகம்', 'iDomain': 'வலைக்கொற்றம்', 'Ignore': 'புறக்கணி', 'Image': 'படிமம்', 'Import': 'இறக்கம்', 'Incompatible': 'முரண்பாடு', 'Indefinite': 'திட்டமிடாத', 'Index': 'சுட்டெண்', 'Index variable': 'சுட்டுமாறி', 'Information': 'தகவல்', 'Information data': 'தகவல் தரவு', 'Information super highways': 'தகவல் மீப் பெருவழிகள்', 'Information technology': 'தகவல் தொழில்நுட்பம்', 'Input unit': 'உள்ளீட்டுப் பகுதி', 'Insert': 'செருகு', 'Install': 'நிறுவு', 'Installation': 'நிறுவுதல்', 'Integrated chips': 'சுற்றமைப்புச் சில்லுகள்', 'Integrated circuit chips': 'ஒருங்கிணைப்பு சுற்றமைப்புச் சில்லுகள்', 'Inter language': 'மொழியிடை', 'Interactive sites': 'ஊடாட்ட தளங்கள்', 'Interests': 'ஆர்வங்கள்', 'Interface': 'இடைமுகப்பு', 'Internal': 'உள்ளக', 'Internal error': 'உள்ளகத் தவறு', 'International': 'பன்னாட்டு', 'International (DNS)': 'பன்னாட்டுக் (கொப்பெகம்)', 'Internet': 'இணையம்', 'Internet protocol address': 'இணைய நெறிமுறை முகவரி', 'Internet protocol (IP)': 'இணைய நெறிமுறை', 'Internet service provider (ISP)': 'இணையச் சேவை வழங்குனர்', 'Interpreter': 'இடைமாற்று', 'Invalid': 'செல்லுபடியாகாத', 'Invention': 'கண்டுப்பிடிப்பு', 'Italic text': 'சாய்வெழுத்து', 'Iteration': 'பன்முறைச் செய்தல்', 'Java script': 'ஜாவா ஆணைத்தொகுதி', 'Key': 'விசை', 'Keyboard': 'தட்டச்சுப்பலகை', 'Keypad': 'விசைத்தளம்', 'Keyword': 'குறிப்புச்சொல்', 'Landscape': 'அகலவாக்கி', 'Laptop computer': 'மடிக்கணினி', 'Layout': 'தளவமைப்பு', 'LCD Monitor': 'திரவ பளிங்குத் திரையகம்', 'Left click': 'இடதுச் சொடுக்கு', 'Lexing error': 'தொகுத்தல் தவறு', 'License': 'உரிமம்', 'Light pen': 'எழுதுகோல்', 'Line': 'வரி', 'Link': 'தொடுப்பு', 'List': 'பட்டியல்', 'Live': 'நேரடி', 'Log in': 'உற்புகு', 'Log out': 'வெளியேறு', 'Machine language': 'பொறிமொழி', 'Machine translation': 'எந்திர மொழிபெயர்ப்பு', 'Magnetic disk': 'காந்த வட்டு', 'Magnetic tape': 'காந்தா நாடா', 'Main Page': 'முகப்புப்பக்கம்', 'Maintenance page': 'மேலாண்மைப் பக்கம்', 'Management': 'முகாமைத்துவம்', 'Mechanical calculator': 'எந்திர கணிப்பான்', 'Media': 'ஊடகம்', 'Media player': 'ஊடக இயக்கி', 'Memory unit': 'நினைவகப் பகுதி', 'Memory': 'நினைவகம்', 'Menu': 'பட்டியல்', 'Metadata': 'தரவு விவரம்', 'Micro processor': 'நுண் செயலி', 'Microphone': 'ஒலிவாங்கி', 'Modem': 'இணக்கி', 'Moderation': 'மட்டுறுத்தல்', 'Moderator': 'மட்டுறுத்துனர்', 'Monetize': 'மதிப்புடைச்செய்', 'Monitor': 'திரையகம்', 'More features': 'கூடுதல் அம்சங்கள்', 'Motherboard': 'தாய்ப்பலகை', 'Mouse': 'சொடுக்கி', 'Multimedia': 'பல்லூடகம்', 'Multitasking': 'பல்பணியாக்கம்', 'My account': 'எனது கணக்கு', 'Natural language': 'இயற்கை மொழி', 'Navigation': 'வழிசெலுத்தல்', 'Negative': 'எதிர்வு', 'Network': 'வலையமைப்பு', 'Networking': 'வலைப்பின்னல்', 'Neutral point of view': 'நடுநிலைநோக்கு', 'New post': 'புதிய இடுகை', 'Non-terminals': 'முடியா முனையங்கள்', 'Notation': 'குறிமானம்', 'Note': 'குறிப்பு', 'Number': 'எண்', 'Numeral': 'எண் முறை', 'Object': 'பொருள்', 'Offline': 'இணைப்பின் வெளியே', 'Online': 'இணைப்பில்', 'Operating system': 'இயங்குக் கட்டகம்', 'Option': 'தேர்வு', 'Orphaned pages': 'உறவிலிப் பக்கங்கள்', 'Other languages': 'ஏனைய மொழிகள்', 'Outsourcing': 'அயலாக்கம்', 'Package': 'பொதி', 'Packets': 'பொதிகள்', 'Page layout': 'பக்க வடிவமைப்பு', 'Page views': 'பக்கப் பார்வைகள்', 'Page': 'பக்கம்', 'Panel': 'பலகை', 'Paperless office': 'தாளில்லா அலுவலகம்', 'Paragraph': 'பந்தி', 'Parallel processing computers': 'இணைச் செயலாக்க கணினிகள்', 'Parent category': 'முதன்மை பக்கவகை', 'Password': 'கடவுச்சொல்', 'Paste': 'ஒட்டு', 'Patch': 'பொருத்து', 'Peripherals': 'உபகரணங்கள்', 'Permission': 'அனுமதி', 'Personal Computer': 'தனி கணினி', 'Photograph': 'புகைப்படம்', 'Picture': 'படம்', 'Piracy': 'களவுநகலாக்கம்', 'Plug in': 'சொருகி', 'Pointer': 'சுட்டு', 'Portable Printer': 'கையடக்க அச்சுப்பொறி', 'Portal': 'வலைவாசல்', 'Post': 'இடுகை', 'Posting': 'இடுகையிடல்', 'Posts': 'இடுகைகள்', 'Preferences': 'விருப்புத்தேர்வுகள்', 'Presentation': 'அளிக்கை', 'Press': 'அமுக்கு', 'Preview': 'முன்தோற்றம்', 'Principals': 'கோட்பாடு', 'Print': 'அச்சிடு', 'Printer': 'அச்சுப்பொறி', 'Privacy': 'தனிமறைவு', 'Problem': 'பிரச்சினை', 'Processor': 'செயலி', 'Program': 'நிரல்', 'Programmers': 'நிரலர்கள்', 'Programming language': 'நிரலாக்க மொழி', 'Prompt': 'தூண்டி', 'Protect': 'காப்புச்செய்', 'Protection log': 'தடைப்பதிகை', 'Protocols': 'நெறிமுறைகள்', 'Proxy Server': 'பதில் சேவையகம்', 'Public domain': 'பொதுக்களம்', 'Publications': 'வெளியீடுகள்', 'Publish': 'வெளியிடு', 'Publisher': 'பதிப்பாளர்', 'Publishing': 'பதிப்பிடல்', 'Query': 'வினவல்', 'RAM': 'நினைவகம்', 'Random Page': 'ஒழுங்கிலாப் பக்கம்', 'Recent changes': 'அண்மைய மாற்றங்கள்', 'Recovery tool': 'மீட்சி கருவி', 'Redirects': 'வழிமாற்றிகள்', 'Redo': 'திரும்பச்செய்', 'Reference desk': 'எடுகோள் மேடை'}
>>> 
>>> d_word.get('Publishing')
...         
'பதிப்பிடல்'
